version: '3.9'

services:
  products-db:
    container_name: products-db-container
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - products-db-volume:/var/lib/postgresql/data

volumes:
  products-db-volume:


